name: Synchronize Labels

on:
  push:
    branches: [main]
    paths:
      - '.github/config/repository-labels.yml'
  schedule:
    - cron: '0 2 1 * *'
  workflow_dispatch:

jobs:
  synchronize-labels:
    name: Synchronize Repository Labels
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Apply Label Configuration
        uses: lukas-kuntze/devx-action-label-manager@main
        with:
          config_file: .github/config/repository-labels.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}
